# Generated by Django 5.1.4 on 2024-12-19 08:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_dashboardmetrics_alter_ticket_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('affected_users', models.IntegerField(default=0)),
                ('system_downtime', models.DurationField(default=datetime.timedelta(0))),
                ('sla_breaches', models.IntegerField(default=0)),
                ('first_response_time', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
        migrations.DeleteModel(
            name='DailyMetrics',
        ),
        migrations.AlterModelOptions(
            name='dashboardmetrics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hourlyticketcount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticketmetrics',
            options={},
        ),
        migrations.RenameField(
            model_name='dashboardmetrics',
            old_name='resolution_time_minutes',
            new_name='active_users',
        ),
        migrations.RenameField(
            model_name='resolutionmetrics',
            old_name='complexity_score',
            new_name='breached_sla',
        ),
        migrations.RenameField(
            model_name='resolutionmetrics',
            old_name='reopened_count',
            new_name='within_sla',
        ),
        migrations.AlterUniqueTogether(
            name='categorydistribution',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hourlyticketcount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prioritymetrics',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='slaconfig',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='recurringpattern',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reportresult',
            name='file',
        ),
        migrations.RemoveField(
            model_name='reportresult',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='resolutionmetrics',
            name='first_response_time',
        ),
        migrations.RemoveField(
            model_name='resolutionmetrics',
            name='resolution_time',
        ),
        migrations.RemoveField(
            model_name='resolutionmetrics',
            name='sla_breached',
        ),
        migrations.RemoveField(
            model_name='resolutionmetrics',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ticketmetrics',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dashboardmetrics',
            name='avg_resolution_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='reportresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportresult',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportresult',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='resolutionmetrics',
            name='avg_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='resolutionmetrics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 12, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resolutionmetrics',
            name='date',
            field=models.DateField(default=datetime.date(2024, 12, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='resolution_time',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='slaconfig',
            name='response_time',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='analyticsdata',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardmetrics',
            name='satisfaction_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prioritymetrics',
            name='avg_resolution_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='frequency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recurringpattern',
            name='potential_cause',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_generated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='parameters',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='schedule',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.report'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ticket'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketmetrics',
            name='avg_resolution_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.RemoveField(
            model_name='categorydistribution',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hourlyticketcount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prioritymetrics',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slaconfig',
            name='resolution_time_threshold',
        ),
        migrations.RemoveField(
            model_name='slaconfig',
            name='response_time_threshold',
        ),
    ]
