version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tmsdb
      POSTGRES_USER: tms_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tms_user -d tmsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: >
      sh -c "while ! nc -z db 5432; do
        echo 'Waiting for database...';
        sleep 1;
      done;
      echo 'Database is ready!';
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=tmsdb
      - DB_USER=tms_user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DEBUG=1
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./tmsapp
    command: sh -c "npm run dev"
    volumes:
      - ./tmsapp:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - HOSTNAME=0.0.0.0
    depends_on:
      - backend

volumes:
  postgres_data: 